CXX = gcc

open_syscall: open_syscall.o
		$(CXX) open_syscall.c -o opens_syscall.o

open_syscall_create: open_syscall_permissions.o
		$(CXX) open_syscall_permissions.c \
			-o open_syscall_permissions.o
#end


